// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id    int64  `json:"id"`
	Token string `json:"token"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id    int64  `json:"id"`
	Token string `json:"token"`
}

type UserInfoResp struct {
	Id    int64  `json:"id"`
	Email string `json:"email"`
	Role  string `json:"role"`
}
