// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	auth "neuro-cloud/apps/auth/api/internal/handler/auth"
	"neuro-cloud/apps/auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 刷新 Token
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
			{
				// 验证 Token
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: auth.VerifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)
}
