// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type LoginReq struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireAt     int64  `json:"expireAt"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RefreshResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireAt     int64  `json:"expireAt"`
}

type VerifyReq struct {
	Token string `json:"token" validate:"required"`
}

type VerifyResp struct {
	Valid   bool   `json:"valid"`
	UserId  string `json:"userId,optional"`
	Email   string `json:"email,optional"`
	Message string `json:"message,optional"`
}
