// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package server

import (
	"context"

	"rpc/internal/logic"
	"rpc/internal/svc"
	"rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 通过用户ID查询
func (s *UserServer) GetUserById(ctx context.Context, in *user.IdReq) (*user.UserInfoResp, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

// 通过邮箱查询
func (s *UserServer) GetUserByEmail(ctx context.Context, in *user.EmailReq) (*user.UserInfoResp, error) {
	l := logic.NewGetUserByEmailLogic(ctx, s.svcCtx)
	return l.GetUserByEmail(in)
}
